/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UniswapV3TwapPriceOracleV2Factory,
  UniswapV3TwapPriceOracleV2FactoryInterface,
} from "../UniswapV3TwapPriceOracleV2Factory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_logic",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "uniswapV3Factory",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "feeTier",
        type: "uint24",
      },
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "logic",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "oracles",
    outputs: [
      {
        internalType: "contract UniswapV3TwapPriceOracleV2",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class UniswapV3TwapPriceOracleV2Factory__factory {
  static readonly abi = _abi;
  static createInterface(): UniswapV3TwapPriceOracleV2FactoryInterface {
    return new utils.Interface(
      _abi
    ) as UniswapV3TwapPriceOracleV2FactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniswapV3TwapPriceOracleV2Factory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UniswapV3TwapPriceOracleV2Factory;
  }
}
