/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        name: "pools",
        outputs: [
            {
                internalType: "string",
                name: "name",
                type: "string",
            },
            {
                internalType: "address",
                name: "creator",
                type: "address",
            },
            {
                internalType: "address",
                name: "comptroller",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "blockPosted",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "timestampPosted",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
export class FuseDirectory__factory {
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
FuseDirectory__factory.abi = _abi;
