/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "underlying",
                type: "address",
            },
        ],
        name: "price",
        outputs: [
            {
                internalType: "uint",
                name: "",
                type: "uint",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
export class MPO__factory {
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
MPO__factory.abi = _abi;
